### PR TITLE
Change "issue this command" to "use this command" and delete trailing whitespace

### PR DESCRIPTION
**Pull request by weixin-you**
Change a word and remove some spaces

### CODE REVIEW

**Comment by gitname** [comment]
Thanks for providing feedback. I consider "issue a command" to be correct, and don't plan to change it. I didn't know the trailing spaces were there, and do plan to delete those next time I update the file.

Reference regarding the phrase, "issue a command":
- https://english.stackexchange.com/questions/431990/run-execute-or-issue-a-command/432018#comment1037157_432018

**Comment by gitname** [comment]
Thanks for providing additional feedback.

I don't plan to merge the latest commit because (a) I think "a pull request that will eventually merged" is not grammatically correct English and (b) the message I want to convey with that sentence is that I add people to the list _when or after_ I merge their contributions, as opposed to beforehand.

When you finish making changes to this branch, will you post a comment here letting me know? That way, I don't merge before you are done making changes to it.

**Comment by weixin-you** [comment]
Thanks. If you do not think it’s appropriate, please just ignore it.

From: gitname ***@***.***>
Date: Saturday, November 12, 2022 at 3:57 PM
To: gitname/react-gh-pages ***@***.***>
Cc: Weixin You ***@***.***>, Author ***@***.***>
Subject: Re: [gitname/react-gh-pages] Change "issue this command" to "use this command" and delete trailing whitespace (PR #116)

Thanks for providing additional feedback.

I don't plan to merge the latest commit because (a) I think "a pull request that will eventually merged" is not grammatically correct English and (b) the message I want to convey with that sentence is that I add people to the list when or after I merge their contributions, as opposed to beforehand.

When you finish making changes to this branch, will you post a comment here letting me know? That way, I don't merge before you are done making changes to it.

**Comment by gitname** [comment]
I removed the whitespace in https://github.com/gitname/react-gh-pages/commit/36c200280b8f4827353aa17c723c056d56d99baf

Thanks again.

**Comment by weixin-you** [comment]
No problem. Thank you for the update.

From: gitname ***@***.***>
Date: Sunday, November 27, 2022 at 7:01 PM
To: gitname/react-gh-pages ***@***.***>
Cc: Weixin You ***@***.***>, Author ***@***.***>
Subject: Re: [gitname/react-gh-pages] Change "issue this command" to "use this command" and delete trailing whitespace (PR #116)

I removed the whitespace in 36c2002<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgitname%2Freact-gh-pages%2Fcommit%2F36c200280b8f4827353aa17c723c056d56d99baf&data=05%7C01%7Cyou00018%40algonquinlive.com%7C8f5283947092498f688108dad0d3bfbe%7Cec1bd9240a6a4aa9aa89c980316c0449%7C0%7C0%7C638051905112462729%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ou89ig8f1xhg7PBnKJFZStcUBZXkIB0%2F9haG2gTtwCU%3D&reserved=0>

Thanks again.

**Pull request closed without merging**
