### PR TITLE
clarification about user.name and user.email in git config

### PR DESCRIPTION
**Pull request by AbhishekCode**
I was stuck at this, i think if you add this in readme it will be lot easier for new user. thanks.

### CODE REVIEW

**Comment by dangpro-1210** [comment]
Huhm. That's great. But I think that  users already know that they have  to sign in in order to push the code to the repos.

**Comment by AbhishekCode** [comment]
yes i agree, in most cases it will be already configured. But still if it is mentioned in documents then it will make it more clear.

**Comment by dangpro-1210** [comment]
It's look like they not mention about adding those.
They should merge!
Again, it would be better for Github Newbie to know that they have to do some configuration

**Comment by gitname** [comment]
Hi @AbhishekCode,

Thanks for telling me you encountered this issue while going through the instructions in this repo. That is useful information for me. While I was writing the instructions, I assumed the reader would already have configured his or her Git client to the point of being able to `$ git push` code to GitHub. Thanks to you, I now know that is not the case.

Thanks for submitting a possible fix for this shortcoming.

Instead of adding a note about configuring a specific aspect (e.g. the `user.name` parameter) of a Git client, I would rather add a 6th prerequisite to the instructions, saying:

> 6. A command-line Git client [setup according to GitHub](https://help.github.com/articles/set-up-git/).

...leaving the details of configuration to someone else (in this case, to GitHub). That way, if the configuration process changes in the future, I won't have to do anything.

You can update this PR with that 6th prerequisite (instead of the note), or discuss further.

**Comment by AbhishekCode** [comment]
Hi @gitname thats actually better way to doing this. i will update this PR

**Pull request merged**
