### PR TITLE
Update README.md - npx create-react-app

### PR DESCRIPTION
**Pull request by adnjoo**
Nice app; I think the following:
```
npx create-react-app react-gh-pages
```
might help users.

### CODE REVIEW

**Comment by gitname** [comment]
Great idea and thank you for suggesting it! I'm in the process of modernizing the instructions and plan to show `npx` instead of `npm` for that particular step.

**Comment by gitname** [comment]
Hi @adnjoo , I updated the instructions today to use `npx`. I actually ended up overhauling the instructions instead of piecing them together from PRs. I want to acknowledge the fact that you contributed this (in my opinion, great) alternative command. Are you OK with me listing you as a contributor at the bottom of the README?

**Comment by adnjoo** [comment]
Hi @gitname thank you, I'm ok with that!

**Comment by gitname** [comment]
Done! Thanks again.

https://github.com/gitname/react-gh-pages#contributors

**Pull request closed without merging**
