### PR TITLE
Added note about selecting correct source branch 

### PR DESCRIPTION
**Pull request by wasp0094**
referencing issue #76

### CODE REVIEW

**Review by jackweyhrich — APPROVED** [review]
LGTM - would like to see this change make it into the documentation, as I was stuck here wondering why my user site was not updating

**Comment by gitname** [comment]
Hi @wasp0094 , thank you for submitting this PR.

Thanks, @jackweyhrich , for sharing your thoughts (and, as a result, bumping this PR in my "feed" 👍 ).

I will add this step to the tutorial (in a position and phrasing TBD).

Question for each of you:
- Are you OK with me adding your avatar to the "Contributors" section at the bottom of the README? (Totally optional)

**Comment by gitname** [comment]
Here's the newly-added step: https://github.com/gitname/react-gh-pages#8-configure-github-pages

If you want me to add your avatar to the README, you can tag (@-mention) me to let me know.

**Comment by jackweyhrich** [comment]
@gitname Thanks very much for merging this in!  I'd be happy to have my avatar added to the README - thanks for the offer!

**Comment by gitname** [comment]
@jackweyhrich Done! You're in the list. :) https://github.com/gitname/react-gh-pages#contributors

**Pull request closed without merging**
